### ISSUE TITLE
Not working on Tailwind CSS 1.1.4

### ISSUE THREAD

**Issue by bymayo** [hacknug/tailwindcss-blend-mode#5]
Installed via npm, then added to plugins:

```
plugins: [
    require('tailwindcss-transforms')({ '3d': false }),
    require('tailwindcss-aspect-ratio')(),
    require('tailwindcss-transitions')(),
    require('tailwindcss-bg-alpha')(),
    require('tailwindcss-blend-mode')
  ]
```

But no classes are rendered in the final output of the CSS in dev (not production) 

Using Tailwind CSS 1.1.4

**Comment by hacknug** [comment]
@bymayo the issue is the docs are not correct. You need to call the required method like this:

```js
require('tailwindcss-blend-mode')(),
```

Sorry for not getting back to you earlier. Hopefully you managed to solve the issue by yourself. This is a documentation error present in most of my plugins and really need to find time to fix it everywhere 😅

**Comment by bymayo** [comment]
@hacknug Yeah a second after I posted the issue, I realised the problem! 😂Thanks for replying though.
